name: Build and deploy Node.js app to Azure Web App - nourish-web-dev-2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare standalone build for deployment
        run: |
          rm -rf deployment
          mkdir -p deployment/.next
          cp -r .next/standalone/* deployment/
          cp -r .next/static deployment/.next/
          cp -r .next/server deployment/.next/ || true
          cp .next/BUILD_ID deployment/.next/ || true
          cp .next/*.json deployment/.next/ || true
          cp -r public deployment/public || true
          cp package.json deployment/
          echo "🧾 Deployment folder content:"
          ls -R deployment

      - name: Zip artifact for deployment
        run: cd deployment && zip -r ../release.zip . && cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: "Deploy to Azure Web App"
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "nourish-web-dev-2"
          slot-name: "Production"
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_721C9718ACDF4A36A3C376F4F5291D93 }}
